-- ════════════════════════════════════════════════════════════════════════
-- manual_trade / manual_cashflow — TMS manual-booking dual-write sink.
--
-- TARGET DB: the tech-team Postgres (prod `production` / uat `uat`) — the SAME
-- store as `fee_event`, NOT the MO DB that holds trades_spot/trades_cashflow.
-- nx-hft-position reads these into its balance ledger (fee_event-style poller).
--
-- This is an ADDITIONAL sink written alongside the existing trades_* booking;
-- it does not touch any existing table. Applied by
-- scripts/apply_schema_manual_tables.py. Idempotent: safe to re-run.
--
-- Design decisions (2026-09-22):
--   * Dense INTEGER refdata asset ids (resolved in TMS from refdata Postgres by
--     codename). `account_id` is TEXT = account_exchange.id + '001' (the '001'
--     sub-account suffix is hardcoded for now), e.g. MOON@BINANCE -> '1001',
--     matching fee_event.account_id TEXT + position's string balance key.
--   * exchange_id was intentionally REMOVED for now (venue->codename mapping
--     undecided); re-add once position needs venue-scoped keys.
--   * portfolio_id / counterparty_id are TMS attribution (MySQL reference_data
--     ids), not consumed by position.
--   * Amend/cancel is SCD2: each amend inserts a NEW version (own entry_uid) and
--     sets effective_date_end on the prior open version. Cancel = an amend with
--     status='cancelled'. Position dedups by entry_uid and reads the current
--     version via effective_date_start/effective_date_end — there is NO
--     reverses_id link.
--   * Per deal_ref, at most one row may be "current" (effective_date_end IS
--     NULL); all prior versions are closed. Enforced by a partial unique index.
-- ════════════════════════════════════════════════════════════════════════

-- ── Enums ───────────────────────────────────────────────────────────────
DO $$ BEGIN
    CREATE TYPE manual_status AS ENUM ('pending','confirmed','processed','settled','cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE manual_trade_side AS ENUM ('buy','sell');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 1:1 with TMS cashflow_type (cashflow_db.VALID_CASHFLOW_TYPES), stored verbatim.
-- If TMS adds a type, extend with: ALTER TYPE manual_cashflow_kind ADD VALUE '<new>';
DO $$ BEGIN
    CREATE TYPE manual_cashflow_kind AS ENUM (
        'INTER PTF FUNDING','RETAINER FEES','OPEX','OPEX - OTHER EXPENSE','OPEX - CONTRA ACC',
        'OTHER INCOME','OTHER EXPENSE','TRANSFER FEES','TRADING FEES','TRADING REWARDS',
        'STRATEGY TESTING EXPENSE','STRATEGY TESTING RETURNED','INTEREST EXPENSE','INTEREST INCOME',
        'WITHHOLDING TAX','LOAN','LOAN REPAYMENT','MARGIN LOAN','MARGIN REPAYMENT','MARGIN SETTLEMENT'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── deal_ref sequences (lineage-key default: MMT###… / MMC###…) ──────────
-- START above any hand-assigned demo refs so auto values never collide.
CREATE SEQUENCE IF NOT EXISTS manual_trade_deal_ref_seq    START 100001;
CREATE SEQUENCE IF NOT EXISTS manual_cashflow_deal_ref_seq START 100001;

-- ── manual_trade ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS manual_trade (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_uid            UUID NOT NULL DEFAULT gen_random_uuid(),  -- position source_ref + writer idempotency
    deal_ref             TEXT NOT NULL DEFAULT ('MMT' || lpad(nextval('manual_trade_deal_ref_seq')::text, 8, '0')),
    external_trade_id    TEXT,

    -- refdata (dense INTEGER ids), except account_id (string, position balance key)
    instrument_id        INTEGER,                 -- nullable (OTC)
    account_id           TEXT    NOT NULL,        -- account_exchange.id + '001' (e.g. MOON@BINANCE -> '1001'); matches fee_event.account_id / position balance key
    base_asset_id        INTEGER NOT NULL,
    quote_asset_id       INTEGER NOT NULL,
    fee_asset_id         INTEGER,
    portfolio_id         INTEGER,                 -- TMS attribution (reference_data id), not position-consumed
    counterparty_id      INTEGER,                 -- TMS attribution (reference_data id), not position-consumed

    raw_symbol           TEXT,
    side                 manual_trade_side NOT NULL,
    quantity             NUMERIC(38,18) NOT NULL,
    price                NUMERIC(38,18) NOT NULL,
    quote_amount         NUMERIC(38,18),
    fee_amount           NUMERIC(38,18),

    status               manual_status NOT NULL DEFAULT 'pending',

    -- clocks
    ts_exchange_event    TIMESTAMPTZ NOT NULL,    -- economic time (position orders by this)
    ts_first_seen        TIMESTAMPTZ NOT NULL DEFAULT now(),  -- ingest/poll cursor
    value_date           DATE,
    effective_date_start TIMESTAMPTZ,             -- TMS mapping only; position ignores
    effective_date_end   TIMESTAMPTZ,

    entity               TEXT,
    txid_reference       TEXT,
    booked_by            TEXT NOT NULL,
    comment              TEXT,

    CONSTRAINT manual_trade_entry_uid_key     UNIQUE (entry_uid),
    CONSTRAINT manual_trade_base_ne_quote     CHECK (base_asset_id <> quote_asset_id),
    CONSTRAINT manual_trade_qty_pos           CHECK (quantity > 0),
    CONSTRAINT manual_trade_price_nonneg      CHECK (price >= 0),
    CONSTRAINT manual_trade_fee_needs_asset   CHECK (fee_amount IS NULL OR fee_asset_id IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS manual_trade_deal_ref_open_key
    ON manual_trade (deal_ref) WHERE effective_date_end IS NULL;
CREATE INDEX IF NOT EXISTS manual_trade_account_time_idx    ON manual_trade (account_id, ts_exchange_event);
CREATE INDEX IF NOT EXISTS manual_trade_first_seen_idx      ON manual_trade (ts_first_seen);
CREATE INDEX IF NOT EXISTS manual_trade_instrument_time_idx ON manual_trade (instrument_id, ts_exchange_event);
CREATE INDEX IF NOT EXISTS manual_trade_deal_ref_idx        ON manual_trade (deal_ref);
CREATE INDEX IF NOT EXISTS manual_trade_open_idx
    ON manual_trade (account_id, ts_exchange_event) WHERE status NOT IN ('settled','cancelled');

-- ── manual_cashflow ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS manual_cashflow (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_uid            UUID NOT NULL DEFAULT gen_random_uuid(),
    deal_ref             TEXT NOT NULL DEFAULT ('MMC' || lpad(nextval('manual_cashflow_deal_ref_seq')::text, 8, '0')),
    external_trade_id    TEXT,

    account_id           TEXT    NOT NULL,        -- account_exchange.id + '001'
    asset_id             INTEGER NOT NULL,
    fee_asset_id         INTEGER,
    portfolio_id         INTEGER,
    counterparty_id      INTEGER,

    kind                 manual_cashflow_kind NOT NULL,
    amount               NUMERIC(38,18) NOT NULL, -- signed (+in / −out)
    fee_amount           NUMERIC(38,18),

    status               manual_status NOT NULL DEFAULT 'pending',

    ts_exchange_event    TIMESTAMPTZ NOT NULL,
    ts_first_seen        TIMESTAMPTZ NOT NULL DEFAULT now(),
    value_date           DATE,
    effective_date_start TIMESTAMPTZ,
    effective_date_end   TIMESTAMPTZ,

    network              TEXT,
    entity               TEXT,
    txid_reference       TEXT,
    booked_by            TEXT NOT NULL,
    comment              TEXT,

    CONSTRAINT manual_cashflow_entry_uid_key   UNIQUE (entry_uid),
    CONSTRAINT manual_cashflow_amount_nonzero  CHECK (amount <> 0),
    CONSTRAINT manual_cashflow_fee_needs_asset CHECK (fee_amount IS NULL OR fee_asset_id IS NOT NULL)
    -- amount sign is derived from booking direction (INCOMING +, OUTGOING −); no
    -- per-kind sign rule, since a given cashflow_type can be either sign.
);

CREATE UNIQUE INDEX IF NOT EXISTS manual_cashflow_deal_ref_open_key
    ON manual_cashflow (deal_ref) WHERE effective_date_end IS NULL;
CREATE INDEX IF NOT EXISTS manual_cashflow_account_time_idx ON manual_cashflow (account_id, ts_exchange_event);
CREATE INDEX IF NOT EXISTS manual_cashflow_first_seen_idx   ON manual_cashflow (ts_first_seen);
CREATE INDEX IF NOT EXISTS manual_cashflow_kind_time_idx    ON manual_cashflow (kind, ts_exchange_event);
CREATE INDEX IF NOT EXISTS manual_cashflow_deal_ref_idx     ON manual_cashflow (deal_ref);
CREATE INDEX IF NOT EXISTS manual_cashflow_open_idx
    ON manual_cashflow (account_id, ts_exchange_event) WHERE status NOT IN ('settled','cancelled');
