-- ════════════════════════════════════════════════════════════════════════
-- manual_transfer — TMS transfer dual-write sink.
--
-- TARGET DB: the tech-team Postgres (prod `production` / uat `uat`), same as
-- manual_trade / manual_cashflow (0001). Written from the MO `transfer` table
-- by scripts/manual_write.py; nx-hft-position reads it into its balance
-- ledger as TransferIn / TransferOut (balance only, never position or P&L).
--
-- Design decisions (2026-09-30):
--   * ONE ROW PER LEG ON ONE OF OUR ACCOUNTS — the position balance key. An
--     INTERNAL MO transfer is a mirror pair (two MO rows) and lands as two
--     rows here, tied by pair_deal_ref; an EXTERNAL transfer is one row, our
--     end being the balance key.
--   * Nothing TMS books is lost, but only ids are stored: both ends'
--     *_account_id verbatim, direction, fee as booked, updated_by,
--     internal_journal, ... Names / products are derivable (our gateway id
--     encodes account + product; the counterparty is counterparty_id) and
--     are not duplicated here.
--   * portfolio_id / counterparty_id mean what they do on 0001 (portfolio
--     number / reference_data counterparty id). The MO transfer row has
--     neither, so they are derived from refdata: portfolio_id from OUR end's
--     account (so the two legs of a cross-portfolio INTERNAL differ), and
--     counterparty_id from the far end's name on an EXTERNAL (NULL on an
--     INTERNAL, whose far end is our own account). NULL when refdata has
--     no match (e.g. a BANK account names only its entity).
--   * OUR end of the leg -- the position balance key, the same TEXT gateway
--     id as manual_cashflow.account_id / fee_event.account_id -- is
--     dest_account_id on an EXTERNAL INCOMING and source_account_id
--     otherwise (INTERNAL legs read from their source; EXTERNAL OUTGOING's
--     source is ours). No separate account_id column duplicates it.
--   * amount is signed on our end: + in / − out.
--   * The fee is paid by the sender: position charges fee_amount against
--     our end only on an outgoing leg (amount < 0). On an incoming leg it
--     is kept as booked (e.g. the counterparty's fee on a deposit) but does
--     not move our balance. The MO side already puts a pair's fee on the
--     outgoing leg only (transfer_db.pair_legs).
--   * Own status enum: the MO transfer lifecycle has COMPLETED, which the
--     shared manual_status does not. Position skips only 'cancelled', so
--     pending / confirmed / completed all move the balance, as on 0001.
--   * Amend/cancel is SCD2 exactly as 0001: a new version (own entry_uid),
--     the prior open version gets effective_date_end. At most one open row
--     per deal_ref (partial unique index).
-- Applied by scripts/apply_schema_manual_tables.py. Idempotent.
-- ════════════════════════════════════════════════════════════════════════

DO $$ BEGIN
    CREATE TYPE manual_transfer_type AS ENUM ('internal','external');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE manual_transfer_status AS ENUM ('pending','confirmed','completed','cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS manual_transfer (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_uid                 UUID NOT NULL DEFAULT gen_random_uuid(),  -- position source_ref + writer idempotency
    deal_ref                  TEXT NOT NULL,           -- MO transfer.deal_ref (MTR########)
    pair_deal_ref             TEXT,                    -- the other leg of an INTERNAL pair; NULL for EXTERNAL / one-sided
    ext_transfer_id           TEXT,                    -- tx hash or venue transfer id

    transfer_type             manual_transfer_type NOT NULL,
    direction                 TEXT NOT NULL CHECK (direction IN ('INCOMING','OUTGOING')), -- MO direction, verbatim
    asset_id                  INTEGER NOT NULL,
    amount                    NUMERIC(38,18) NOT NULL, -- signed on our end (+in / −out)
    fee_asset_id              INTEGER,
    fee_amount                NUMERIC(38,18),          -- as booked in TMS; position charges it on an outgoing leg only
    portfolio_id              INTEGER,                 -- portfolio NUMBER of our end's account (refdata); TMS attribution, not position-consumed
    counterparty_id           INTEGER,                 -- reference_data counterparty id of the far end (EXTERNAL only); TMS attribution

    -- Both ends' ids exactly as TMS booked them (MO transfer.*_account_id).
    -- Ours is dest on an EXTERNAL INCOMING, else source -- the position
    -- balance key, NOT NULL by manual_transfer_own_end_id below. Names and
    -- products are not stored: our gateway id encodes account + product,
    -- and the counterparty is counterparty_id.
    source_account_id         TEXT,                    -- gateway id (ours) or wallet address / venue ref (counterparty)
    dest_account_id           TEXT,

    network                   TEXT,
    internal_journal          BOOLEAN NOT NULL DEFAULT false,

    status                    manual_transfer_status NOT NULL DEFAULT 'pending',

    -- clocks
    ts_exchange_event         TIMESTAMPTZ NOT NULL,    -- COALESCE(completed, initiated); position orders by this
    ts_initiated              TIMESTAMPTZ NOT NULL,
    ts_completed              TIMESTAMPTZ,
    ts_first_seen             TIMESTAMPTZ NOT NULL DEFAULT now(),
    effective_date_start      TIMESTAMPTZ,
    effective_date_end        TIMESTAMPTZ,

    booked_by                 TEXT NOT NULL,           -- MO user_id (Created By)
    updated_by                TEXT,                    -- MO updated_by (who made this version)
    comment                   TEXT,

    CONSTRAINT manual_transfer_entry_uid_key   UNIQUE (entry_uid),
    CONSTRAINT manual_transfer_amount_nonzero  CHECK (amount <> 0),
    CONSTRAINT manual_transfer_fee_needs_asset CHECK (fee_amount IS NULL OR fee_asset_id IS NOT NULL),
    CONSTRAINT manual_transfer_own_end_id      CHECK (
        CASE WHEN transfer_type = 'external' AND direction = 'INCOMING'
             THEN dest_account_id IS NOT NULL
             ELSE source_account_id IS NOT NULL END)
);

CREATE UNIQUE INDEX IF NOT EXISTS manual_transfer_deal_ref_open_key
    ON manual_transfer (deal_ref) WHERE effective_date_end IS NULL;
CREATE INDEX IF NOT EXISTS manual_transfer_source_time_idx  ON manual_transfer (source_account_id, ts_exchange_event);
CREATE INDEX IF NOT EXISTS manual_transfer_dest_time_idx    ON manual_transfer (dest_account_id, ts_exchange_event);
CREATE INDEX IF NOT EXISTS manual_transfer_first_seen_idx   ON manual_transfer (ts_first_seen);
CREATE INDEX IF NOT EXISTS manual_transfer_deal_ref_idx     ON manual_transfer (deal_ref);
CREATE INDEX IF NOT EXISTS manual_transfer_pair_idx         ON manual_transfer (pair_deal_ref) WHERE pair_deal_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS manual_transfer_ext_id_idx       ON manual_transfer (ext_transfer_id) WHERE ext_transfer_id IS NOT NULL;
