"""Apply the trades_cashflow schema + trade_seq_cashflow sequence to UAT Postgres.

Idempotent: uses CREATE ... IF NOT EXISTS so re-running is safe.
Reads credentials from the `#MO DB UAT` block in /.env.
"""
import os
from pathlib import Path
import psycopg2

REPO = Path(__file__).resolve().parents[1]
ENV = REPO / ".env"


def _load_creds() -> dict[str, str]:
    """Env vars (MO_DB_*) take precedence; .env file parsed as fallback."""
    env_creds = {
        k: os.environ[f"MO_DB_{k.upper()}"]
        for k in ("host", "port", "database", "username", "password")
        if f"MO_DB_{k.upper()}" in os.environ
    }
    if all(k in env_creds for k in ("host", "database", "username", "password")):
        env_creds.setdefault("port", "5432")
        return env_creds

    creds: dict[str, str] = {}
    in_block = False
    for line in ENV.read_text(encoding="utf-8", errors="replace").splitlines():
        s = line.strip()
        if "MO DB UAT" in s.upper():
            in_block = True
            continue
        if not in_block:
            continue
        if not s or s.startswith("#"):
            if s.startswith("#") and "MO DB UAT" not in s.upper():
                break
            continue
        if ":" in s:
            k, _, v = s.partition(":")
            key = k.strip().lower()
            if key.startswith("mo_db_"):
                key = key[len("mo_db_"):]
            creds[key] = v.strip()
    return creds


DDL = """
-- ════════════════════════════════════════════════════════════════
-- trade_seq_cashflow — monotonic counter for MCF deal-refs.
-- Standardized floor: new environments begin at 4578 so MCF refs align
-- across UAT and PROD (set 2026-06-05). IF NOT EXISTS means this never
-- resets an existing sequence — use scripts/set_cashflow_seq.py for that.
-- ════════════════════════════════════════════════════════════════
CREATE SEQUENCE IF NOT EXISTS trade_seq_cashflow
  START WITH 4578 INCREMENT BY 1 NO MAXVALUE CACHE 1;

-- ════════════════════════════════════════════════════════════════
-- trades_cashflow — bitemporal cashflow trades.
-- Column order matches the form JSON payload key sequence
-- (see trade-booking/docs/cashflow-schema-mapping.md) so backend
-- INSERTs and SELECT * round-trip in the same shape as the form.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS trades_cashflow (
  deal_ref            TEXT           NOT NULL
                        DEFAULT ('MCF' || lpad(nextval('trade_seq_cashflow')::text, 8, '0')),
  external_trade_id   TEXT,
  txn_type            TEXT           NOT NULL DEFAULT 'CASHFLOW',
  cashflow_type       TEXT           NOT NULL,
  direction           TEXT           NOT NULL
                        CHECK (direction IN ('INCOMING','OUTGOING')),
  entity              TEXT           NOT NULL,
  portfolio_id        TEXT           NOT NULL,
  portfolio_name      TEXT           NOT NULL,
  counterparty_id     TEXT,
  counterparty        TEXT,
  account             TEXT,
  account_type        TEXT,
  asset               TEXT           NOT NULL,
  amount              NUMERIC(36,18) NOT NULL,
  fee_asset           TEXT,
  fee_amount          NUMERIC(36,18) DEFAULT 0,
  trade_date          TIMESTAMPTZ    NOT NULL,
  value_date          TIMESTAMPTZ    NOT NULL,
  network             TEXT,
  txid_reference      TEXT,
  effective_start     TIMESTAMPTZ    NOT NULL,
  effective_end       TIMESTAMPTZ,
  user_id             TEXT           NOT NULL,
  status              TEXT           NOT NULL
                        CHECK (status IN
                          ('PENDING','CONFIRMED','PROCESSED','SETTLED','CANCELLED')),
  comment             TEXT,
  id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY (id),
  CONSTRAINT uq_trades_cashflow_version UNIQUE (deal_ref, effective_start)
);

CREATE INDEX IF NOT EXISTS idx_tcf_live
  ON trades_cashflow (deal_ref) WHERE effective_end IS NULL;
CREATE INDEX IF NOT EXISTS idx_tcf_deal_ref
  ON trades_cashflow (deal_ref);
CREATE INDEX IF NOT EXISTS idx_tcf_portfolio
  ON trades_cashflow (portfolio_id);
CREATE INDEX IF NOT EXISTS idx_tcf_external_trade_id
  ON trades_cashflow (external_trade_id) WHERE external_trade_id IS NOT NULL;
"""


def main():
    c = _load_creds()
    conn = psycopg2.connect(
        host=c["host"],
        port=int(c.get("port", "5432")),
        dbname=c["database"],
        user=c["username"],
        password=c["password"],
        connect_timeout=15,
    )
    conn.autocommit = True
    cur = conn.cursor()
    cur.execute(DDL)
    print("applied DDL OK\n")

    # Verify
    cur.execute("""
        SELECT column_name, data_type, is_nullable, column_default
        FROM information_schema.columns
        WHERE table_name = 'trades_cashflow'
        ORDER BY ordinal_position
    """)
    cols = cur.fetchall()
    print(f"trades_cashflow columns: {len(cols)}")
    for col in cols:
        print(f"  {col[0]:20s} {col[1]:20s} {'NULL' if col[2]=='YES' else 'NOT NULL':10s} {col[3] or ''}")

    cur.execute(
        "SELECT sequencename, start_value, last_value, increment_by "
        "FROM pg_sequences WHERE sequencename='trade_seq_cashflow'"
    )
    seq = cur.fetchone()
    print(f"\nsequence: {seq}")

    cur.execute("""
        SELECT indexname FROM pg_indexes
        WHERE tablename='trades_cashflow'
        ORDER BY indexname
    """)
    idx = [r[0] for r in cur.fetchall()]
    print(f"\nindexes: {idx}")

    cur.execute("SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='trades_cashflow'::regclass ORDER BY contype")
    print("\nconstraints:")
    for row in cur.fetchall():
        print(f"  {row[0]}")

    conn.close()


if __name__ == "__main__":
    main()
