"""Apply the trades_transfer schema + trade_seq_transfer sequence. Idempotent.

A transfer is a MOVEMENT of an asset from one account to another, not an
economic event: it changes where a position sits, never P&L. It gets its
own table so the P&L engine, which reads trades_cashflow, never sees one.

One row per transfer, both ends on it. Column order approved 2026-09-28:
id first, then the deal_ref, the movement, the two ends, the amounts,
the timing, the SCD2 window, then authorship and status.

  transfer_type  INTERNAL: both ends are our accounts, booked OUTGOING from
                 the source's point of view (amount negative).
                 EXTERNAL: one end is ours, the other a counterparty; that
                 end's *_account_name is the counterparty name, its product
                 is NULL and its *_account_id is a wallet address or venue
                 reference typed by the user.
  direction      INCOMING = amount positive, OUTGOING = amount negative.
  fee_amount     paid by the source on top of `amount`.

No portfolio column: transfers are admin-only until scoping is rebuilt on
account -> portfolio.

Reads MO_DB_* env vars, else the `# MO DB UAT` block in /.env.
"""
from __future__ import annotations
import cashflow_db


DDL = """
CREATE SEQUENCE IF NOT EXISTS trade_seq_transfer
  START WITH 1 INCREMENT BY 1 NO MAXVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS trades_transfer (
  id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY,
  deal_ref            TEXT           NOT NULL
                        DEFAULT ('MTR' || lpad(nextval('trade_seq_transfer')::text, 8, '0')),
  transfer_type       TEXT           NOT NULL
                        CHECK (transfer_type IN ('INTERNAL','EXTERNAL')),
  direction           TEXT           NOT NULL
                        CHECK (direction IN ('INCOMING','OUTGOING')),
  source_account_name TEXT           NOT NULL,
  source_product      TEXT,
  source_account_id   TEXT,
  dest_account_name   TEXT           NOT NULL,
  dest_product        TEXT,
  dest_account_id     TEXT,
  asset               TEXT           NOT NULL,
  amount              NUMERIC(36,18) NOT NULL,
  fee_asset           TEXT,
  fee_amount          NUMERIC(36,18) DEFAULT 0,
  initiated_datetime  TIMESTAMPTZ    NOT NULL,
  completed_datetime  TIMESTAMPTZ,
  network             TEXT,
  ext_transfer_id     TEXT,
  effective_start     TIMESTAMPTZ    NOT NULL,
  effective_end       TIMESTAMPTZ,
  user_id             TEXT           NOT NULL,
  status              TEXT           NOT NULL
                        CHECK (status IN
                          ('PENDING','CONFIRMED','PROCESSED','SETTLED','CANCELLED')),
  comment             TEXT,
  updated_by          TEXT,
  PRIMARY KEY (id),
  CONSTRAINT uq_trades_transfer_version UNIQUE (deal_ref, effective_start)
);

CREATE INDEX IF NOT EXISTS idx_ttr_live
  ON trades_transfer (deal_ref) WHERE effective_end IS NULL;
CREATE INDEX IF NOT EXISTS idx_ttr_deal_ref
  ON trades_transfer (deal_ref);
-- The venue's own id is the natural "already booked?" key once withdrawal
-- and deposit feeds start landing here.
CREATE INDEX IF NOT EXISTS idx_ttr_ext_transfer_id
  ON trades_transfer (ext_transfer_id) WHERE ext_transfer_id IS NOT NULL;
"""


def main() -> None:
    conn = cashflow_db.connect()
    try:
        with conn:
            with conn.cursor() as cur:
                cur.execute(DDL)
                cur.execute(
                    "SELECT column_name, data_type, is_nullable "
                    "  FROM information_schema.columns "
                    " WHERE table_name = 'trades_transfer' "
                    " ORDER BY ordinal_position"
                )
                cols = cur.fetchall()
        print(f"applied DDL OK - trades_transfer has {len(cols)} columns")
        for name, typ, nullable in cols:
            print(f"  {name:20s} {typ:28s} {'NULL' if nullable == 'YES' else 'NOT NULL'}")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
